Fix for rec

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -138,25 +138,25 @@ $LATESTARTSERVICE && cp -af $INSTALLER/common/service.sh $MODPATH/service.sh
 
 # migrating fonts.xml
 ui_print "- Migrating fonts.xml"
-IMGPATH=/sbin/.core/img
-MIRRORPATH=/sbin/.core/mirror
-FONTS=fonts.xml
-FONTSPATH=/system/etc/
-FINALPATH=$IMGPATH/.core/$FONTS
-if [ -f $FONTSPATH$FONTS -o -f $MIRRORPATH$FONTSPATH$FONTS ]; then
-  mkdir -p $MODPATH$FONTSPATH
+[[ -d /sbin/.core/img ]] && IMGPATH=/sbin/.core/img || IMGPATH=/dev/tmp/magisk_img
+[[ -d /sbin/.core/mirror ]] && MIRRORPATH=/sbin/.core/mirror || unset MIRRORPATH
+FILE=fonts.xml
+FILEPATH=/system/etc/
+FINALPATH=/.core/
+if [ -f $MIRRORPATH$FILEPATH$FILE ]; then
+  mkdir -p $MODPATH$FILEPATH
   if [ ! -d $IMGPATH/notosanscjk-nougat ]; then
     ui_print "- Skipping compatability fixes"
-    [[ -f $MIRRORPATH$FONTSPATH$FONTS ]] && cp -af $MIRRORPATH$FONTSPATH$FONTS $FINALPATH || cp -af $FONTSPATH$FONTS $FINALPATH
+    cp -af $MIRRORPATH$FILEPATH$FILE $IMGPATH$FINALPATH$FILE
   fi
-  ln -sf $FINALPATH $MODPATH$FONTSPATH$FONTS
-  sed -i '/<family lang=\"und-Zsye\">/,/<\/family>/ {/<\/family>/! d;/<\/family>/ s/.*/<family lang="und-Zsye">\n<font weight="400" style="normal">NotoColorEmoji-old.ttf<\/font>\n<\/family>\n<family lang="und-Zsye">\n<font weight="400" style="normal">NotoColorEmoji.ttf<\/font>\n<\/family>/};/^$/d' $FINALPATH
+  ln -sf /sbin/.core/img$FINALPATH$FILE $MODPATH$FILEPATH$FILE
+  sed -i '/<family lang=\"und-Zsye\">/,/<\/family>/ {/<\/family>/! d;/<\/family>/ s/.*/<family lang="und-Zsye">\n<font weight="400" style="normal">NotoColorEmoji-old.ttf<\/font>\n<\/family>\n<family lang="und-Zsye">\n<font weight="400" style="normal">NotoColorEmoji.ttf<\/font>\n<\/family>/};/^$/d' $IMGPATH$FINALPATH$FILE
 else
   ui_print "- Migration FAILED. Nothing have done to your system."
 fi
 
-# fallback compatability
-[[ -f $FINALPATH ]] || { rm -rf $MODPATH$FONTSPATH$FONTS && ui_print "! Error ! Please Upload log to the developer.";}
+# failover
+[[ -f $IMGPATH$FINALPATH$FILE ]] || { rm -rf $MODPATH$FILEPATH$FILE && ui_print "! Error ! Please Upload log to the developer.";}
 
 ui_print "- Setting permissions"
 set_permissions
